//! The keymap page, written from the keymap.
//!
//! `keymap::HELP` is what `f1` draws and what the command palette searches. A
//! second copy of it in a documentation file would be correct on the day it
//! was written and wrong on the day after — so there is no second copy: `site
//! sync` regenerates the page, and CI fails when the committed one no longer
//! matches. The same arrangement as the screenshots, for the same reason.

use std::fmt::Write as _;

use trafford::keymap::HELP;

pub const PATH: &str = "keys.md";

const HEADER: &str = "\
---
order: 95
section: Reference
description: Every key trafford binds, generated from the keymap itself.
---

# Keys

<!-- Generated by `site sync` from trafford/src/keymap.rs. Do not edit: your
     change would be overwritten by the next sync, and CI would fail first. -->

This is the same table `f1` draws, written out of the same list. If a key here
is wrong, the program is wrong.

";

/// The page, as markdown.
pub fn page() -> String {
    let mut out = String::from(HEADER);
    let mut open = false;
    for (key, description) in HELP {
        // A row with no key and a description is a section heading; a row with
        // neither is the blank line between two of them.
        if key.is_empty() {
            if description.is_empty() {
                continue;
            }
            if open {
                out.push('\n');
            }
            let _ = write!(
                out,
                "## {}\n\n| Key | What it does |\n| --- | --- |\n",
                title_case(description)
            );
            open = true;
            continue;
        }
        let _ = writeln!(out, "| {} | {} |", key_cell(key), escape_cell(description));
    }
    out
}

/// Draw the left-hand column, which holds two different things.
///
/// Most rows are keys — `za zR zM` is three of them and each should read as
/// one. But the mouse section's rows are gestures written as prose (`click a
/// folder`, `menu key`), and setting those in `code` gives `click` `a`
/// `folder`, which reads like three keystrokes.
fn key_cell(raw: &str) -> String {
    if raw.split_whitespace().all(is_key) {
        raw.split_whitespace()
            .map(|k| format!("`{k}`"))
            .collect::<Vec<_>>()
            .join(" ")
    } else {
        escape_cell(raw)
    }
}

/// Whether one token names a key rather than being a word in a sentence.
fn is_key(token: &str) -> bool {
    const NAMED: [&str; 6] = ["enter", "space", "esc", "tab", "wheel", "drag"];
    token.chars().count() <= 3
        || token.starts_with("ctrl-")
        || token.starts_with("alt-")
        || token.starts_with("shift-")
        || NAMED.contains(&token)
        || (token.starts_with('f') && token[1..].parse::<u8>().is_ok())
}

/// Make a description safe to sit in a table cell.
///
/// Two collisions, both real. A pipe would end the cell early and make the
/// whole table ragged, so it takes Obsidian's own escape — which the table
/// parser already understands. And `[[link]]` appears in several descriptions
/// as *the syntax*, not as a link to a note called "link"; drawn as a link it
/// would resolve to nothing and fail the build, which is the build being
/// right. It is code, so it is marked up as code.
fn escape_cell(s: &str) -> String {
    let escaped = s.replace('|', "\\|");
    let mut out = String::with_capacity(escaped.len());
    let mut rest = escaped.as_str();
    // Built left to right rather than replaced in place: wrapping `[[x]]` in
    // backticks leaves a `[[` behind, and a loop that searches the whole
    // string again finds it forever. It did, for five minutes.
    while let Some(open) = rest.find("[[") {
        let Some(close) = rest[open..].find("]]").map(|at| at + open + 2) else {
            break;
        };
        out.push_str(&rest[..open]);
        out.push('`');
        out.push_str(&rest[open..close]);
        out.push('`');
        rest = &rest[close..];
    }
    out.push_str(rest);
    out
}

/// `EDITOR (vim-flavoured)` reads as shouting in a heading.
fn title_case(s: &str) -> String {
    let lower = s.to_lowercase();
    let mut chars = lower.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_binding_in_the_program_reaches_the_page() {
        let page = page();
        for (key, description) in HELP {
            if key.is_empty() {
                continue;
            }
            assert!(
                page.contains(&escape_cell(description)),
                "{description} is bound but not documented"
            );
            assert!(
                page.contains(&key_cell(key)),
                "{key} is bound but not on the page"
            );
        }
    }

    /// The mouse rows are sentences, not keystrokes, and drawing them as code
    /// makes `click a folder` read as three keys.
    #[test]
    fn a_gesture_written_as_prose_is_not_set_as_keys() {
        assert_eq!(key_cell("za zR zM"), "`za` `zR` `zM`");
        assert_eq!(key_cell("ctrl-p"), "`ctrl-p`");
        assert_eq!(
            key_cell("h j k l w b 0 ^ $"),
            "`h` `j` `k` `l` `w` `b` `0` `^` `$`"
        );
        assert_eq!(key_cell("click a folder"), "click a folder");
        assert_eq!(key_cell("menu key"), "menu key");
        assert_eq!(key_cell("shift-drag"), "`shift-drag`");
        assert_eq!(key_cell("f1"), "`f1`");
    }

    #[test]
    fn the_page_is_deterministic() {
        assert_eq!(page(), page());
    }

    /// A description containing a pipe would otherwise split its row and make
    /// the whole table ragged, which the table parser then refuses to draw.
    #[test]
    fn a_pipe_in_a_description_does_not_break_the_table() {
        assert_eq!(escape_cell("a | b"), "a \\| b");
    }

    /// `[[link]]` in a description is the syntax being named, not a link to a
    /// note called "link" — which does not exist, and would fail the build.
    #[test]
    fn a_literal_wikilink_in_a_description_is_marked_up_as_code() {
        assert_eq!(
            escape_cell("follow the [[link]] under the cursor"),
            "follow the `[[link]]` under the cursor"
        );
    }
}
